name: Docker

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BASE_IMAGE: [14.13-debian, 15.5-debian, 15.8-debian, 16.4-debian]
        PGVECTORS_VERSION: ["0.2.1"] # https://github.com/tensorchord/pgvecto.rs/releases/tag/v0.2.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/niklasrosenstein/cnpg-postgresql-pgvectors:${{ matrix.BASE_IMAGE }}-pgvectors-${{ matrix.PGVECTORS_VERSION }}}
          cache-to: type=registry,ref=ghcr.io/niklasrosenstein/cnpg-postgresql-pgvectors/cache:${{ matrix.BASE_IMAGE }}-pgvectors-${{ matrix.PGVECTORS_VERSION }}},mode=max
          cache-from: type=registry,ref=ghcr.io/niklasrosenstein/cnpg-postgresql-pgvectors/cache:${{ matrix.BASE_IMAGE }}-pgvectors-${{ matrix.PGVECTORS_VERSION }}}
          platforms: linux/amd64,linux/arm64
          args: |
            BASE_IMAGE=${{ matrix.BASE_IMAGE }}
            PGVECTORS_VERSION=${{ matrix.PGVECTORS_VERSION }}
